COVID

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt

In [2]:
import plotly.express as px
import nbformat
import plotly.graph_objects as go

In [3]:
covid = pd.read_csv("Covid-19-cases.csv")

In [4]:
covid.head()

          Entity Code         Day  New cases (per 1M)
0  United States  USA  2020-03-01            0.013803
1  United States  USA  2020-03-02            0.014222
2  United States  USA  2020-03-03            0.021751
3  United States  USA  2020-03-04            0.034717
4  United States  USA  2020-03-05            0.054377

In [7]:
covid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1177 entries, 0 to 1176
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Entity              1177 non-null   object
 1   Code                1177 non-null   object
 2   Day                 1177 non-null   datetime64[ns]
 3   New cases (per 1M)  1177 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(2)
memory usage: 36.9+ KB

In [6]:
covid['Day'] = pd.to_datetime(covid['Day'])

In [17]:
#Resample (best for time series)
monthly = covid.set_index('Day').resample('M').sum()

C:\Users\ecbas\AppData\Local\Temp\ipykernel_25176\2954637481.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly = covid.set_index('Day').resample('M').sum()

In [41]:
covid.head()

          Entity Code        Day  New cases (per 1M)  New cases (actual)
0  United States  USA 2020-03-01            0.013803           1380.3268
1  United States  USA 2020-03-02            0.014222           1422.1548
2  United States  USA 2020-03-03            0.021751           2175.0603
3  United States  USA 2020-03-04            0.034717           3471.7310
4  United States  USA 2020-03-05            0.054377           5437.6510

In [38]:
covid['New cases (actual)'] = covid['New cases (actual)'] * 1000000

In [42]:
fig = px.line(
    covid,
    x='Day',
    y='New cases (actual)',
    title='Covid Cases (Actual Numbers)'
)

fig.show()

In [21]:
#plot chart

fig = px.line(covid, x='Day', y='New cases (actual)', title='Covid Cases')
#fig.update_layout(xaxis_title='Month/Year', yaxis_title='Revuenue per mile(Millions)', 
#                  width=800,  height=600,)


fig.show()